### ISSUE TITLE
Errors on huxtable 5.0.0

### ISSUE THREAD

**Issue by hughjonesd** [atorus-research/pharmaRTF#2]
Hi guys,

I've been running reverse dependency checks on huxtable dependencies. pharmaRTF currently gets a couple of errors in running examples:

```
*   checking examples ... ERROR
  
    > library(huxtable)
    
 ...
    > ht <- huxtable(
    +   column1 = 1:5,
    +   column2 = letters[1:5]
    + )
    > rtf <- rtf_doc(ht, list(hf_line("aTitle")))
    > 
    > header_rows(rtf)
    Error in UseMethod("header_rows") : 
      no applicable method for 'header_rows' applied to an object of class "rtf_doc"
    Calls: header_rows
    Execution halted
```

I guess `header_rows` is a pharmaRTF method that is now getting interfered with by the new huxtable generic and function, of the same name.

I also get some testing failures:

```
      [ OK: 212 | SKIPPED: 0 | WARNINGS: 1 | FAILED: 5 ]
      1. Error: insert_buffer adds a blank column correctly (@test_helpers.r#37) 
      2. Failure: hf_string orderes lines properly (@test_rtf-code-generators.r#24) 
      3. Failure: header_string lines populates correctly (@test_rtf-code-generators.r#123) 
      4. Failure: header_string lines populates correctly (@test_rtf-code-generators.r#124) 
      5. Failure: rtf_doc returns a list with a table, title, and footnotes (@test_rtf_doc.r#14) 
```

You can test the latest version of huxtable with

```
remotes::install_github("hughjonesd/huxtable")
```

The master branch is now in bugfix-only mode.

**Comment by atorus-research** [comment]
Thank you @hughjonesd. We'll get this fixed this week.

**Comment by hughjonesd** [comment]
Great. I am going to submit to CRAN shortly and will mention this in my submission comments.

**Comment by atorus-research** [comment]
Hey @hughjonesd, pharmaRTF 0.1.1 has been submitted to CRAN and it is playing well with Huxtable v5.

**Comment by hughjonesd** [comment]
Thanks guys, great stuff.
